server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true # 开启ip注册
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
spring:
  application:
    name: consumer-service  #服务名，serviceId
